### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'bool'

### ISSUE THREAD

**Issue by Aidenkwok** [gafsel/flutter_plugin_playlist#1]
Can't seem to alter the playlist after it has been initialised through addItem, addAllItems,  or setPlaylistItems methods.

It gives me the error "type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'bool'"

**Comment by gafsel** [comment]
Hello @Aidenkwok 

Can you send me more details on how you're invoking the methods and how you're handling there return values?

**Comment by gafsel** [comment]
Hey @Aidenkwok 

I think I was able to replicate the problem by calling addItem. Couldn't get that specific error by calling addAllItems or setPlaylistItems though... 

If you provide me with more info I can reopen the issue.

**Comment by gafsel** [comment]
@Aidenkwok fix it on release v0.1.1
