### ISSUE TITLE
Behavior of Prev button

### ISSUE THREAD

**Issue by phimath** [gafsel/flutter_plugin_playlist#10]
Is there any way to change the behavior of the previous button in the notification player / bluetooth?

In my app when I hit previous, it first checks how far into the current track the song is.  If it is within the first few seconds, it goes to the previous track in the playlist, but if it is later in the track, it restarts the current track. I believe most audio players function this way.

This works fine inside of the app, but I would like to have Bluetooth and the lock screen player function similarly.  Is there any way to achieve this?

thanks!

**Comment by gafsel** [comment]
Hi @phimath 

Release 0.1.4 should provide this behavior. 
If the action is called before 3 seconds it will return to the previews track. If it is called after 3 seconds it will return to the start of the current track.
