### ISSUE TITLE
Load audio files from flutter local assets

### ISSUE THREAD

**Issue by Sun3** [gafsel/flutter_plugin_playlist#12]
I would like to request a new feature to add the ability to load audio files from the flutter local assets folder.

Thanks, great plugin.

**Comment by gafsel** [comment]
Hey there @Sun3 

Release 0.1.4 should provide this feature. 
You can reference asset tracks and thumbnails by adding the prefix asset:// to the asset path.
I put an example of how you can do this in the plugin.
