### ISSUE TITLE
play/pause button doesn't work in control center on IOS

### ISSUE THREAD

**Issue by hosseinbahmanabadi** [gafsel/flutter_plugin_playlist#13]
ios version 13.0

**Comment by Aidenkwok** [comment]
@gafsel play/pause on iOS 13 doesn't work for me either which causes the app to crash. I don't think it's just play/pause... I think there are other methods that don't work with iOS 13.

**Comment by luiz-simples** [comment]
Me too!

`2019-10-30 18:34:48.823203-0400 Runner[794:189448] * Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported action method signature. Must return MPRemoteCommandHandlerStatus or take a completion handler as the second argument.'`

**Comment by luiz-simples** [comment]
```
* First throw call stack:
(...)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by luiz-simples** [comment]
https://forums.developer.apple.com/thread/121540#thread-message-378018

**Comment by meh111** [comment]
it seems this bug is already fixed in cordova repo, but not merged https://github.com/Rolamix/cordova-plugin-playlist/issues/36

**Comment by gafsel** [comment]
Hello everyone,

As @meh111  mentioned I got the solution from the original plugin and it seems to work.
I Tested it my environment and seems to ben ok in release 0.1.4.
Let me know if you guys have any more problems.

**Comment by hosseinbahmanabadi** [comment]
ohh thank you very much
