### ISSUE TITLE
Events listener example

### ISSUE THREAD

**Issue by newdev8** [gafsel/flutter_plugin_playlist#19]
Hello, I'm trying to implement the event listener as shown in the example:

player.on('status', (eventName, arguments) {

   // TODO handle the status update

});

but I can't seem to implement it correctly (it gives me a syntax error), can anyone show a full example of how to implement it and use it? Thanks.

**Comment by gafsel** [comment]
Hi there @lain-ke,

The docs is not updated. Sorry about that.

The correct syntax should use named parameters for the arguments, as follows:

rmxAudioPlayer.on('status', (eventName, {dynamic args}) {

});

I'll fix the docs.
