### ISSUE TITLE
Any way to add item / items at a specified index instead of the end of the queue?

### ISSUE THREAD

**Issue by phimath** [gafsel/flutter_plugin_playlist#3]
First of all, thank you so much for porting this plugin to flutter!  Its so much nicer to work with than the other available plugins.

Is there a simple way to add tracks to the middle of the queue, without stopping the currently playing track?

**Comment by gafsel** [comment]
Hi @phimath, thanks for the feedback!

I'm working on it. Already did the Android code. 
Hoping to release a new version with the iOS and some more fixes in a couple of days max.

**Comment by gafsel** [comment]
@phimath add and index parameter in the methods addAllItems and addItem on release v0.1.1
