### ISSUE TITLE
How to change icon of notification?

### ISSUE THREAD

**Issue by phimath** [gafsel/flutter_plugin_playlist#4]
The default icon in the media notification is the Flutter logo.  How do you go about changing this?

thanks

**Comment by gafsel** [comment]
Hi @phimath 

You can change the icon by adding the new one at res/mipmap/icon.png.

**Comment by phimath** [comment]
Thanks, figured out though that its res/mipmap/ic_launcher.png  that changes it if you want to update the docs to reflect.

**Comment by gafsel** [comment]
I revised the source code and find out that it expects mipmap/icon and if it is not found, the mipmap/ic_laucher is requested, as shown below: 

    private int getMipmapIcon() {
        // return R.mipmap.icon; // this comes from cordova itself.
        if (notificationIconId <= 0) {
            notificationIconId = fakeR.getId("mipmap", "icon");
            // API 28 moves the reference to this.
            if (notificationIconId <= 0) {
                notificationIconId = fakeR.getId("mipmap", "ic_launcher");
            }
        }
        return notificationIconId;
    }

I'll change the plugin so it can receive any chosen name.
