### ISSUE TITLE
Only way to play music is with setPlaylistIems

### ISSUE THREAD

**Issue by phimath** [gafsel/flutter_plugin_playlist#5]
I'm finding the only way I can successfully play music is with `setPlaylistItems`.

If I do `addAllItems` and then `play`,  `play` throws:
`PlatformException (PlatformException(PLAY, PLAY, false))`

If I do `playTrackByIndex`, it throws:
`PlatformException (PlatformException(error, java.util.HashMap cannot be cast to java.lang.Number, null))`

I'm not sure what I'm doing wrong with these calls.  Is there an example of adding items to a playlist that already exists and then playing them?

**Comment by gafsel** [comment]
Hello @phimath 

Thanks for the feedback. Woking on it. I'll probably release the new version in a couple of days.

**Comment by phimath** [comment]
Awesome, thank you!

**Comment by gafsel** [comment]
@phimath problem fixed on release v0.1.1
