### ISSUE TITLE
PlatformException on removeItem()

### ISSUE THREAD

**Issue by phimath** [gafsel/flutter_plugin_playlist#6]
When I call:

`rmxAudioPlayer.removeItem(AudioTrackRemoval(trackIndex: index));`

I get this exception:
`PlatformException (PlatformException(error, java.util.HashMap cannot be cast to java.lang.Number, null))`

Also thanks for the 1.1 release!  This plugin is great to use!

**Comment by gafsel** [comment]
@phimath done.

Any problems, let me know!

**Comment by phimath** [comment]
I'm getting this issue when building  with 0.1.2 now.

```

.pub-cache/hosted/pub.dartlang.org/flutter_plugin_playlist-0.1.2/android/src/main/java/org/gafs/flutter_plugin_playlist/FlutterPluginPlaylistPlugin.java:146: error: incompatible types: String cannot be converted to int
      int trackIndex = option((Number) removal.get("trackIndex"), -1).intValue();
                                                   ^
.pub-cache/hosted/pub.dartlang.org/flutter_plugin_playlist-0.1.2/android/src/main/java/org/gafs/flutter_plugin_playlist/FlutterPluginPlaylistPlugin.java:147: error: incompatible types: String cannot be converted to int
      String trackId = option((String) removal.get("trackId"), "");
                                                   ^
Note: .pub-cache/hosted/pub.dartlang.org/flutter_plugin_playlist-0.1.2/android/src/main/java/org/gafs/flutter_plugin_playlist/service/MediaImageProvider.java uses or overrides a deprecated API.
```

**Comment by gafsel** [comment]
Sorry about that =S

I belive now it will work.

Again, any problems, let me know!

**Comment by phimath** [comment]
Yep this fixes it, thank you!

However, upon removing any track, the current track restarts.  Is there a way to leave the current track playing when removing other tracks?

**Comment by gafsel** [comment]
I believe it is possible. I'll try to change its behavior.
